### ISSUE TITLE
Using pipe operator instead of "+" (or additionally)

### ISSUE THREAD

**Issue by SebaStad** [ianmoran11/mmtable2#14]
This is less of a request but more of a question: Have you thought about using the '%>%' operator instead of the ggplot-like '+', or at least allow both?

While it makes sense to copy features from the original, [Hadley himself](https://community.rstudio.com/t/why-cant-ggplot2-use/4372/7) mentioned that he would prefer if ggplot could handle the pipe, but cant for historical reasons.

**Comment by ianmoran11** [comment]
Great question @SebaStad ! The use of the addition operator was very intentional - I wanted the package to mirror the syntax of ggplot2 since so many people are familiar with it.  Using the pipe syntax instead may have been more straightforward in terms of implementation. 

That said, including an option for both doesn't seem to introduce any major complications. I've put together a minimal example in this [pipesyntax branch](https://github.com/ianmoran11/mmtable2/tree/pipesyntax) (see the second last section of the readme). I'll aim to keep the option of a pipe operator in combination with the "add_" prefix. I can't see this causing any problems down the track, but if it does I'll prioritise the original + syntax. 

Thanks for the suggestion!

**Comment by ianmoran11** [comment]
2669ba1a6f06af2990934ca5a2cd9773c312c9b7
